[workspace]
members = [".", "tools/xtask"]
resolver = "3"

[workspace.package]
version = "0.0.1"
edition = "2024"
rust-version = "1.88"
license = "MIT"

[package]
name = "nera"
version.workspace = true
description = "Compiler for the Nera systems programming language"
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "nera"
path = "src/main.rs"

[[bin]]
name = "nera-frontend-fuzz"
path = "src/bin/nera_frontend_fuzz.rs"

[[bin]]
name = "nera-verifier-fuzz"
path = "src/bin/nera_verifier_fuzz.rs"

[lints.rust]
missing_debug_implementations = "warn"
unsafe_code = "forbid"
