use crate::GateStep;

use super::{Regression, RegressionEntry};
use crate::regression::checks::*;

pub(super) const ENTRIES: &[RegressionEntry] = &[
    (
        GateStep::Place,
        Regression {
            check: check_place_regression,
            tests: &[
                "hir_program",
                "hir_place",
                "hir_public_api",
                "vir_v0",
                "vir_memory_schema",
                "vir_corpus",
                "vir_interpreter",
                "native_abi",
                "native_acceptance",
                "native_assembly",
                "native_codegen",
                "native_memory_codegen",
                "native_plan",
                "verifier_transfer",
                "verifier_cfg",
                "verifier_contracts",
                "verifier_cases",
                "verifier_complex_cases",
                "verifier_properties",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::ControlFlow,
        Regression {
            check: check_control_flow_regression,
            tests: &[
                "frontend_corpus",
                "frontend_control_flow",
                "frontend_calls",
                "frontend_loops",
                "frontend_for_match",
                "hir_program",
                "hir_control",
                "hir_public_api",
                "vir_v0",
                "vir_corpus",
                "vir_interpreter",
                "verifier_cfg",
                "verifier_contracts",
                "native_abi",
                "native_plan",
                "native_codegen",
                "native_acceptance",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::VirUnit,
        Regression {
            check: check_vir_unit_regression,
            tests: &[
                "frontend_calls",
                "hir_program",
                "hir_public_api",
                "hir_spec",
                "vir_unit_baseline",
                "vir_source_map",
                "vir_contracts",
                "typed_spec_ir",
                "ghost_non_interference",
                "vir_v0",
                "vir_corpus",
                "vir_interpreter",
                "verifier_cfg",
                "verifier_contracts",
                "native_plan",
                "native_codegen",
                "native_acceptance",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Aggregate,
        Regression {
            check: check_aggregate_regression,
            tests: &[
                "hir_program",
                "hir_place",
                "hir_public_api",
                "frontend_aggregates",
                "frontend_enums",
                "aggregate_abi",
                "vir_v0",
                "vir_memory_schema",
                "vir_object_shape",
                "vir_object_effect",
                "vir_slice_range",
                "verifier_object_state",
                "object_effect_runtime",
                "vir_local_storage",
                "vir_corpus",
                "vir_interpreter",
                "verifier_transfer",
                "verifier_cfg",
                "verifier_contracts",
                "verifier_cases",
                "verifier_properties",
                "native_abi",
                "native_plan",
                "native_codegen",
                "native_memory_codegen",
                "native_acceptance",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
];
