use crate::GateStep;

use super::{Regression, RegressionEntry};
use crate::regression::checks::*;

pub(super) const ENTRIES: &[RegressionEntry] = &[
    (
        GateStep::Phase721BorrowBaseline,
        Regression {
            check: check_phase7_borrow_baseline_regression,
            tests: &[
                "borrow_baseline",
                "hir_place",
                "aggregate_abi",
                "vir_slice_range",
            ],
            library: true,
            snapshots: false,
            native: false,
        },
    ),
    (
        GateStep::Phase722HirBorrowRegions,
        Regression {
            check: check_phase7_hir_borrow_regions_regression,
            tests: &["borrow_baseline", "hir_regions", "hir_place", "hir_program"],
            library: true,
            snapshots: false,
            native: false,
        },
    ),
    (
        GateStep::Phase723VirLoanSchema,
        Regression {
            check: check_phase7_vir_loan_schema_regression,
            tests: &[
                "vir_loan_schema",
                "borrow_baseline",
                "hir_regions",
                "vir_source_map",
                "vir_unit_baseline",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase724VerifierLoans,
        Regression {
            check: check_phase7_verifier_loans_regression,
            tests: &[
                "verifier_loans",
                "vir_loan_schema",
                "borrow_baseline",
                "hir_regions",
                "verifier_cfg",
                "verifier_guarded",
                "verifier_transfer",
            ],
            library: true,
            snapshots: false,
            native: false,
        },
    ),
    (
        GateStep::Phase725LoanConsumers,
        Regression {
            check: check_phase7_loan_consumers_regression,
            tests: &[
                "loan_consumers",
                "vir_loan_schema",
                "verifier_loans",
                "ghost_non_interference",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase726LocalSharedBorrow,
        Regression {
            check: check_phase7_local_shared_borrow_regression,
            tests: &[
                "frontend_shared_borrow",
                "borrow_baseline",
                "hir_regions",
                "vir_loan_schema",
                "verifier_loans",
                "loan_consumers",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase727LocalMutableBorrow,
        Regression {
            check: check_phase7_local_mutable_borrow_regression,
            tests: &[
                "frontend_mutable_borrow",
                "frontend_shared_borrow",
                "borrow_baseline",
                "hir_regions",
                "vir_loan_schema",
                "verifier_loans",
                "loan_consumers",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase728Reborrow,
        Regression {
            check: check_phase7_reborrow_regression,
            tests: &[
                "frontend_reborrow",
                "frontend_mutable_borrow",
                "frontend_shared_borrow",
                "hir_regions",
                "vir_loan_schema",
                "verifier_loans",
                "loan_consumers",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase729LoweringArchitecture,
        Regression {
            check: check_phase7_lowering_architecture_regression,
            tests: &[
                "runtime_semantics",
                "vir_corpus",
                "vir_source_map",
                "frontend_aggregates",
                "frontend_calls",
                "frontend_reborrow",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase7210NllEndPlanning,
        Regression {
            check: check_phase7_nll_regression,
            tests: &[
                "frontend_nll",
                "frontend_reborrow",
                "frontend_mutable_borrow",
                "frontend_shared_borrow",
                "hir_regions",
                "vir_loan_schema",
                "verifier_loans",
                "vir_source_map",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase7211GuardedLoanCfg,
        Regression {
            check: check_phase7_loan_cfg_regression,
            tests: &[
                "frontend_shared_borrow",
                "frontend_nll",
                "frontend_reborrow",
                "frontend_loops",
                "verifier_loans",
                "verifier_guarded",
                "loan_consumers",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase7212ReferenceAggregate,
        Regression {
            check: check_phase7_reference_aggregate_regression,
            tests: &[
                "frontend_reference_aggregate",
                "frontend_shared_borrow",
                "frontend_mutable_borrow",
                "frontend_reborrow",
                "vir_loan_schema",
                "verifier_loans",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase7213SafeSlice,
        Regression {
            check: check_phase7_safe_slice_regression,
            tests: &[
                "frontend_safe_slice",
                "frontend_reborrow",
                "vir_slice_range",
                "vir_loan_schema",
                "verifier_loans",
                "loan_consumers",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase7214BorrowCalls,
        Regression {
            check: check_phase7_borrow_calls_regression,
            tests: &[
                "frontend_borrow_calls",
                "frontend_calls",
                "frontend_safe_slice",
                "loan_consumers",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase7215BorrowAcceptance,
        Regression {
            check: check_phase7_borrow_acceptance,
            tests: &[
                "stage7_borrow_acceptance",
                "borrow_baseline",
                "hir_regions",
                "vir_loan_schema",
                "verifier_loans",
                "verifier_guarded",
                "frontend_shared_borrow",
                "frontend_mutable_borrow",
                "frontend_reborrow",
                "frontend_nll",
                "frontend_reference_aggregate",
                "frontend_safe_slice",
                "frontend_borrow_calls",
                "loan_consumers",
                "ghost_non_interference",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
];
