use crate::GateStep;

use super::{Regression, RegressionEntry};
use crate::regression::checks::*;

pub(super) const ENTRIES: &[RegressionEntry] = &[
    (
        GateStep::Phase751ProvenanceBaseline,
        Regression {
            check: check_phase7_provenance_baseline,
            tests: &[
                "provenance_baseline",
                "hir_place",
                "verifier_transfer",
                "verifier_cases",
                "verifier_cfg",
                "verifier_guarded",
                "verifier_contracts",
                "vir_memory_schema",
                "loan_consumers",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase755PointerDomain,
        Regression {
            check: check_phase7_pointer_domain,
            tests: &[
                "pointer_domain",
                "raw_address",
                "provenance_schema",
                "provenance_instance",
                "provenance_baseline",
                "symbolic_footprint",
                "relation_bounds",
                "relation_audit",
                "verifier_transfer",
                "verifier_cfg",
                "verifier_contracts",
                "loan_consumers",
                "frontend_borrow_calls",
                "vir_memory_schema",
                "vir_slice_range",
                "runtime_semantics",
                "vir_unit_baseline",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase756PointerComparison,
        Regression {
            check: check_phase7_pointer_comparison,
            tests: &[
                "pointer_comparison",
                "pointer_domain",
                "raw_address",
                "provenance_instance",
                "relation_audit",
                "verifier_contracts",
                "vir_unit_baseline",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase758AddressModel,
        Regression {
            check: check_phase7_address_model,
            tests: &[
                "native_address_model",
                "native_acceptance",
                "native_plan",
                "native_abi",
                "native_codegen",
                "native_memory_codegen",
                "native_assembly",
                "ghost_non_interference",
                "raw_address",
                "pointer_domain",
                "pointer_comparison",
                "provenance_instance",
                "provenance_flow",
                "runtime_semantics",
                "vir_source_map",
                "vir_unit_baseline",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase759ProvenanceAudit,
        Regression {
            check: check_phase7_provenance_audit,
            tests: &[
                "provenance_audit",
                "relation_audit",
                "provenance_instance",
                "provenance_flow",
                "pointer_comparison",
                "pointer_domain",
                "raw_address",
                "verifier_guarded",
                "verifier_cfg",
                "verifier_cases",
                "native_address_model",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase7510ProvenanceAcceptance,
        Regression {
            check: check_phase7_provenance_acceptance,
            tests: &[
                "stage7_provenance_acceptance",
                "provenance_audit",
                "provenance_flow",
                "provenance_instance",
                "provenance_schema",
                "provenance_baseline",
                "pointer_comparison",
                "pointer_domain",
                "raw_address",
                "native_address_model",
                "native_acceptance",
                "ghost_non_interference",
                "verifier_guarded",
                "verifier_properties",
                "vir_unit_baseline",
                "vir_source_map",
                "frontend_nll",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase757ProvenanceFlow,
        Regression {
            check: check_phase7_provenance_flow,
            tests: &[
                "provenance_flow",
                "pointer_comparison",
                "pointer_domain",
                "provenance_instance",
                "frontend_borrow_calls",
                "frontend_reference_aggregate",
                "frontend_aggregate_transfer",
                "verifier_guarded",
                "verifier_contracts",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase754RawAddress,
        Regression {
            check: check_phase7_raw_address,
            tests: &[
                "raw_address",
                "provenance_schema",
                "provenance_instance",
                "provenance_baseline",
                "hir_place",
                "vir_unit_baseline",
                "vir_source_map",
                "loan_consumers",
                "verifier_transfer",
                "verifier_cfg",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase753AllocationInstance,
        Regression {
            check: check_phase7_allocation_instance,
            tests: &[
                "provenance_instance",
                "provenance_schema",
                "provenance_baseline",
                "verifier_cfg",
                "verifier_contracts",
                "verifier_transfer",
                "verifier_properties",
                "frontend_loop_initialization",
                "loan_consumers",
                "native_acceptance",
                "vir_interpreter",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase752ProvenanceSchema,
        Regression {
            check: check_phase7_provenance_schema,
            tests: &[
                "provenance_schema",
                "provenance_baseline",
                "vir_memory_schema",
                "vir_object_shape",
                "vir_slice_range",
                "vir_source_map",
                "verifier_cases",
                "verifier_transfer",
                "loan_consumers",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
];
