use crate::GateStep;

use super::{Regression, RegressionEntry};
use crate::regression::checks::*;

pub(super) const ENTRIES: &[RegressionEntry] = &[
    (
        GateStep::Phase765ConditionalSummary,
        Regression {
            check: check_phase7_conditional_summary,
            tests: &[
                "summary_conditional",
                "summary_calls",
                "summary_projection",
                "summary_baseline",
                "frontend_initialization_interfaces",
                "frontend_borrow_calls",
                "verifier_guarded",
                "provenance_instance",
                "provenance_flow",
                "stage7_provenance_acceptance",
                "relation_composition",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase767RecursiveSummary,
        Regression {
            check: check_phase7_recursive_summary,
            tests: &[
                "summary_recursive",
                "summary_borrows",
                "summary_conditional",
                "summary_calls",
                "summary_projection",
                "summary_baseline",
                "frontend_borrow_calls",
                "frontend_aggregates",
                "verifier_loans",
                "verifier_guarded",
                "provenance_flow",
                "provenance_instance",
                "relation_composition",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase768SummaryAcceptance,
        Regression {
            check: check_phase7_summary_acceptance,
            tests: &[
                "summary_audit",
                "summary_recursive",
                "summary_borrows",
                "summary_conditional",
                "summary_calls",
                "summary_projection",
                "summary_baseline",
                "provenance_audit",
                "relation_audit",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase766BorrowSummary,
        Regression {
            check: check_phase7_borrow_summary,
            tests: &[
                "summary_borrows",
                "summary_conditional",
                "summary_calls",
                "summary_projection",
                "frontend_borrow_calls",
                "frontend_reference_aggregate",
                "frontend_reborrow",
                "verifier_loans",
                "loan_consumers",
                "stage7_borrow_acceptance",
                "frontend_initialization_interfaces",
                "provenance_instance",
                "relation_composition",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase764SummaryCalls,
        Regression {
            check: check_phase7_summary_calls,
            tests: &[
                "summary_calls",
                "summary_projection",
                "summary_baseline",
                "summary_architecture",
                "frontend_borrow_calls",
                "frontend_initialization_interfaces",
                "verifier_contracts",
                "verifier_guarded",
                "provenance_instance",
                "provenance_flow",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase763SummaryProjection,
        Regression {
            check: check_phase7_summary_projection,
            tests: &[
                "summary_projection",
                "summary_baseline",
                "summary_architecture",
                "verifier_cfg",
                "verifier_guarded",
                "verifier_contracts",
                "frontend_initialization_interfaces",
                "frontend_borrow_calls",
                "provenance_flow",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase762SummaryArchitecture,
        Regression {
            check: check_phase7_summary_architecture,
            tests: &[
                "summary_architecture",
                "summary_baseline",
                "typed_spec_ir",
                "frontend_nll",
                "frontend_borrow_calls",
                "frontend_aggregate_transfer",
                "frontend_initialization_interfaces",
                "verifier_transfer",
                "verifier_contracts",
                "provenance_audit",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase761SummaryBaseline,
        Regression {
            check: check_phase7_summary_baseline,
            tests: &[
                "summary_baseline",
                "frontend_borrow_calls",
                "frontend_initialization_interfaces",
                "frontend_aggregate_transfer",
                "provenance_flow",
                "verifier_contracts",
                "runtime_semantics",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: false,
            snapshots: true,
            native: true,
        },
    ),
];
