use crate::GateStep;

use super::{Regression, RegressionEntry};
use crate::regression::checks::*;

pub(super) const ENTRIES: &[RegressionEntry] = &[
    (
        GateStep::Phase741RelationBaseline,
        Regression {
            check: check_phase7_relation_baseline,
            tests: &[
                "relation_baseline",
                "verifier_cfg",
                "verifier_object_state",
                "frontend_safe_slice",
                "frontend_reborrow",
                "frontend_borrow_calls",
                "frontend_loop_initialization",
                "frontend_initialization_interfaces",
                "stage7_initialization_acceptance",
                "ghost_non_interference",
                "native_acceptance",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase742DifferenceRelations,
        Regression {
            check: check_phase7_difference_relations,
            tests: &[
                "difference_relations",
                "relation_baseline",
                "verifier_cfg",
                "frontend_safe_slice",
                "frontend_loop_initialization",
                "frontend_reborrow",
                "stage7_initialization_acceptance",
                "ghost_non_interference",
                "native_acceptance",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase743RelationCfg,
        Regression {
            check: check_phase7_relation_cfg,
            tests: &[
                "relation_cfg",
                "difference_relations",
                "relation_baseline",
                "verifier_cfg",
                "verifier_guarded",
                "frontend_loop_initialization",
                "frontend_safe_slice",
                "frontend_borrow_calls",
                "stage7_borrow_acceptance",
                "stage7_initialization_acceptance",
                "ghost_non_interference",
                "native_acceptance",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase744SymbolicFootprint,
        Regression {
            check: check_phase7_symbolic_footprint,
            tests: &[
                "symbolic_footprint",
                "relation_cfg",
                "verifier_loans",
                "loan_consumers",
                "frontend_safe_slice",
                "frontend_reference_aggregate",
                "frontend_reborrow",
                "frontend_borrow_calls",
                "stage7_borrow_acceptance",
                "ghost_non_interference",
                "native_acceptance",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase745RelationBounds,
        Regression {
            check: check_phase7_relation_bounds,
            tests: &[
                "relation_bounds",
                "relation_baseline",
                "relation_cfg",
                "difference_relations",
                "symbolic_footprint",
                "frontend_safe_slice",
                "frontend_borrow_calls",
                "frontend_reborrow",
                "stage7_borrow_acceptance",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase746DisjointElements,
        Regression {
            check: check_phase7_disjoint_elements,
            tests: &[
                "disjoint_elements",
                "relation_bounds",
                "relation_baseline",
                "difference_relations",
                "relation_cfg",
                "symbolic_footprint",
                "verifier_loans",
                "loan_consumers",
                "frontend_reference_aggregate",
                "frontend_safe_slice",
                "frontend_reborrow",
                "stage7_borrow_acceptance",
                "object_effect_runtime",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase747SiblingSlices,
        Regression {
            check: check_phase7_sibling_slices,
            tests: &[
                "sibling_slices",
                "disjoint_elements",
                "relation_bounds",
                "relation_baseline",
                "vir_loan_schema",
                "verifier_loans",
                "loan_consumers",
                "frontend_safe_slice",
                "frontend_reborrow",
                "frontend_nll",
                "frontend_reference_aggregate",
                "frontend_borrow_calls",
                "stage7_borrow_acceptance",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase748StridedRegions,
        Regression {
            check: check_phase7_strided_regions,
            tests: &[
                "strided_regions",
                "sibling_slices",
                "disjoint_elements",
                "relation_bounds",
                "difference_relations",
                "relation_baseline",
                "relation_cfg",
                "symbolic_footprint",
                "verifier_loans",
                "loan_consumers",
                "object_effect_runtime",
                "frontend_safe_slice",
                "frontend_reborrow",
                "stage7_borrow_acceptance",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase749RelationComposition,
        Regression {
            check: check_phase7_relation_composition,
            tests: &[
                "relation_composition",
                "frontend_loop_initialization",
                "frontend_initialization_interfaces",
                "stage7_initialization_acceptance",
                "relation_cfg",
                "relation_bounds",
                "symbolic_footprint",
                "strided_regions",
                "sibling_slices",
                "frontend_borrow_calls",
                "frontend_safe_slice",
                "verifier_loans",
                "loan_consumers",
                "stage7_borrow_acceptance",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase7410RelationAudit,
        Regression {
            check: check_phase7_relation_audit,
            tests: &[
                "relation_audit",
                "relation_baseline",
                "difference_relations",
                "relation_cfg",
                "relation_bounds",
                "strided_regions",
                "relation_composition",
                "sibling_slices",
                "verifier_guarded",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase7411RelationAcceptance,
        Regression {
            check: check_phase7_relation_acceptance,
            tests: &[
                "stage7_relation_acceptance",
                "relation_audit",
                "relation_baseline",
                "difference_relations",
                "relation_cfg",
                "relation_bounds",
                "disjoint_elements",
                "symbolic_footprint",
                "sibling_slices",
                "strided_regions",
                "relation_composition",
                "vir_loan_schema",
                "vir_memory_schema",
                "verifier_guarded",
                "verifier_loans",
                "loan_consumers",
                "frontend_nll",
                "stage7_borrow_acceptance",
                "stage7_initialization_acceptance",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
];
