use crate::GateStep;

use super::{Regression, RegressionEntry};
use crate::regression::checks::*;

pub(super) const ENTRIES: &[RegressionEntry] = &[
    (
        GateStep::Phase731InitializationBaseline,
        Regression {
            check: check_phase7_initialization_baseline,
            tests: &[
                "initialization_baseline",
                "frontend_deferred_local",
                "verifier_object_state",
                "object_effect_runtime",
                "vir_object_effect",
                "vir_object_shape",
                "resource_payload",
                "frontend_copy_move",
                "frontend_drop",
                "frontend_aggregate_transfer",
                "frontend_reference_aggregate",
                "frontend_borrow_calls",
                "verifier_guarded",
                "stage7_resource_acceptance",
                "loan_consumers",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase732InitializationPlanning,
        Regression {
            check: check_phase7_initialization_planning,
            tests: &[
                "initialization_baseline",
                "frontend_deferred_local",
                "initialization_planning",
                "frontend_drop",
                "frontend_copy_move",
                "frontend_reference_aggregate",
                "frontend_borrow_calls",
                "frontend_safe_slice",
                "verifier_loans",
                "loan_consumers",
                "vir_loan_schema",
                "stage7_borrow_acceptance",
                "object_effect_runtime",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase733DeferredLocal,
        Regression {
            check: check_phase7_deferred_local,
            tests: &[
                "frontend_deferred_local",
                "initialization_baseline",
                "initialization_planning",
                "hir_program",
                "hir_regions",
                "loan_consumers",
                "verifier_object_state",
                "object_effect_runtime",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase734PartialRefill,
        Regression {
            check: check_phase7_partial_refill,
            tests: &[
                "frontend_partial_refill",
                "frontend_reference_aggregate",
                "initialization_planning",
                "resource_payload",
                "loan_consumers",
                "verifier_object_state",
                "object_effect_runtime",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase735PartialConstruction,
        Regression {
            check: check_phase7_partial_construction,
            tests: &[
                "frontend_partial_construction",
                "frontend_partial_refill",
                "frontend_deferred_local",
                "frontend_reference_aggregate",
                "resource_payload",
                "loan_consumers",
                "initialization_planning",
                "verifier_object_state",
                "object_effect_runtime",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase736EnumConstruction,
        Regression {
            check: check_phase7_enum_construction,
            tests: &[
                "frontend_enum_construction",
                "frontend_enums",
                "frontend_reference_aggregate",
                "frontend_partial_construction",
                "verifier_object_state",
                "object_effect_runtime",
                "loan_consumers",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase737HeapConstruction,
        Regression {
            check: check_phase7_heap_construction,
            tests: &[
                "frontend_heap_construction",
                "frontend_enum_construction",
                "frontend_partial_construction",
                "verifier_object_state",
                "object_effect_runtime",
                "native_plan",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase738LoopInitialization,
        Regression {
            check: check_phase7_loop_initialization,
            tests: &[
                "frontend_loop_initialization",
                "frontend_heap_construction",
                "verifier_cfg",
                "verifier_contracts",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase739InitializationInterfaces,
        Regression {
            check: check_phase7_initialization_interfaces,
            tests: &[
                "frontend_initialization_interfaces",
                "frontend_borrow_calls",
                "frontend_aggregate_transfer",
                "aggregate_abi",
                "verifier_contracts",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase7310InitializationAcceptance,
        Regression {
            check: check_phase7_initialization_acceptance,
            tests: &[
                "stage7_initialization_acceptance",
                "initialization_baseline",
                "initialization_planning",
                "frontend_deferred_local",
                "frontend_partial_refill",
                "frontend_partial_construction",
                "frontend_enum_construction",
                "frontend_heap_construction",
                "frontend_loop_initialization",
                "frontend_initialization_interfaces",
                "vir_object_shape",
                "verifier_object_state",
                "ghost_non_interference",
                "native_acceptance",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
];
