use crate::GateStep;

use super::{Regression, RegressionEntry};
use crate::regression::checks::*;

pub(super) const ENTRIES: &[RegressionEntry] = &[
    (
        GateStep::Phase7832BorrowInterfaceMapping,
        Regression {
            check: check_phase7_borrow_interface_mapping,
            tests: &[
                "borrow_interface_mapping",
                "hir_regions",
                "aggregate_abi",
                "frontend_borrow_calls",
                "implicit_borrow_baseline",
                "implicit_lifetime_syntax",
                "summary_borrows",
                "summary_recursive",
                "generic_instances",
                "native_abi",
                "loan_consumers",
                "stage7_borrow_acceptance",
                "frontend_copy_move",
                "frontend_deferred_local",
                "frontend_partial_construction",
                "resource_payload",
                "vir_loan_schema",
                "vir_unit_baseline",
                "vir_source_map",
                "vir_v0",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase7833ImplicitBorrowInference,
        Regression {
            check: check_phase7_implicit_borrow_inference,
            tests: &[
                "implicit_borrow_inference",
                "implicit_borrow_baseline",
                "borrow_interface_mapping",
                "frontend_borrow_calls",
                "frontend_reborrow",
                "implicit_lifetime_syntax",
                "summary_borrows",
                "loan_consumers",
                "generic_instances",
                "module_program",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase7834ConditionalBorrowInference,
        Regression {
            check: check_phase7_conditional_borrow_inference,
            tests: &[
                "conditional_borrow_inference",
                "implicit_borrow_inference",
                "frontend_borrow_calls",
                "summary_borrows",
                "loan_consumers",
                "hir_regions",
                "vir_unit_baseline",
                "vir_source_map",
                "vir_loan_schema",
                "resource_payload",
                "frontend_copy_move",
                "frontend_deferred_local",
                "frontend_partial_construction",
                "vir_v0",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase7835BorrowProjection,
        Regression {
            check: check_phase7_borrow_projection,
            tests: &[
                "borrow_projection",
                "borrow_interface_mapping",
                "conditional_borrow_inference",
                "frontend_safe_slice",
                "summary_borrows",
                "loan_consumers",
                "hir_regions",
                "vir_unit_baseline",
                "vir_source_map",
                "vir_loan_schema",
                "resource_payload",
                "vir_v0",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase7836BorrowSourceScc,
        Regression {
            check: check_phase7_borrow_source_scc,
            tests: &[
                "borrow_source_scc",
                "implicit_borrow_inference",
                "conditional_borrow_inference",
                "borrow_projection",
                "summary_recursive",
                "summary_borrows",
                "frontend_loops",
                "hir_regions",
                "vir_loan_schema",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase7837ImplicitLifetimeSyntax,
        Regression {
            check: check_phase7_implicit_lifetime_syntax,
            tests: &[
                "implicit_lifetime_syntax",
                "generic_instances",
                "module_program",
                "implicit_borrow_inference",
                "conditional_borrow_inference",
                "borrow_projection",
                "frontend_properties",
                "hir_regions",
                "summary_borrows",
            ],
            library: true,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase7838ImplicitBorrowAcceptance,
        Regression {
            check: check_phase7_implicit_borrow_acceptance,
            tests: &[
                "implicit_borrow_acceptance",
                "implicit_lifetime_syntax",
                "implicit_borrow_baseline",
                "borrow_interface_mapping",
                "implicit_borrow_inference",
                "conditional_borrow_inference",
                "borrow_projection",
                "borrow_source_scc",
                "verification_text",
                "verification_report",
                "generic_instances",
                "module_program",
                "summary_borrows",
                "summary_audit",
                "frontend_nll",
                "frontend_reference_aggregate",
                "vir_loan_schema",
                "ghost_non_interference",
                "verification_fail_closed",
                "native_acceptance",
                "frontend_properties",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase784CapabilityProfile,
        Regression {
            check: check_phase7_capability_profile,
            tests: &[
                "capability_profile",
                "compilation_session",
                "implicit_lifetime_syntax",
                "verification_text",
                "verify_cli",
            ],
            library: false,
            snapshots: false,
            native: false,
        },
    ),
    (
        GateStep::Phase785InterfaceArtifact,
        Regression {
            check: check_phase7_interface_artifact,
            tests: &[
                "interface_artifact",
                "capability_profile",
                "compilation_session",
                "generic_instances",
                "module_program",
            ],
            library: false,
            snapshots: false,
            native: false,
        },
    ),
    (
        GateStep::Phase786StageAcceptance,
        Regression {
            check: check_phase7_stage_acceptance,
            tests: &[
                "stage7_8_acceptance",
                "interface_artifact",
                "implicit_borrow_acceptance",
                "generic_instances",
                "module_program",
                "compilation_session",
                "capability_profile",
                "summary_baseline",
                "verification_fail_closed",
            ],
            library: false,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase7831ImplicitBorrowBaseline,
        Regression {
            check: check_phase7_implicit_borrow_baseline,
            tests: &[
                "implicit_borrow_baseline",
                "frontend_borrow_calls",
                "frontend_initialization_interfaces",
                "implicit_lifetime_syntax",
                "summary_baseline",
                "summary_borrows",
                "summary_recursive",
                "generic_instances",
            ],
            library: false,
            snapshots: false,
            native: true,
        },
    ),
    (
        GateStep::Phase783GenericInstances,
        Regression {
            check: check_phase7_generic_instances,
            tests: &[
                "generic_instances",
                "module_program",
                "compilation_session",
                "frontend_properties",
                "frontend_copy_move",
                "verification_text",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase783NamedLifetimes,
        Regression {
            check: check_phase7_implicit_lifetime_syntax,
            tests: &[
                "implicit_lifetime_syntax",
                "generic_instances",
                "frontend_calls",
                "frontend_reborrow",
                "borrow_baseline",
                "summary_borrows",
                "hir_program",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase782ModuleProgram,
        Regression {
            check: check_phase7_module_program,
            tests: &[
                "module_program",
                "compilation_session",
                "verification_report",
                "verification_text",
                "verify_cli",
                "hir_program",
                "summary_recursive",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
    (
        GateStep::Phase781CompilationSession,
        Regression {
            check: check_phase7_compilation_session,
            tests: &[
                "compilation_session",
                "verification_report",
                "verification_text",
                "verification_fail_closed",
                "verify_cli",
                "typed_spec_ir",
                "native_acceptance",
                "ghost_non_interference",
            ],
            library: true,
            snapshots: true,
            native: true,
        },
    ),
];
